version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: video_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  app:
    image: video2-app
    container_name: app-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
